#!/bin/bash
#$ -V
#$ -cwd
#$ -j y
#$ -pe orte 1
#$ -p 0
#$ -R y
#$ -hold_jid qch_recovertest_001_B0_30_S0_3
#$ -N equ_recovertest_001_B0_30_S0_3_T490000
#$ -o ./equilibration/submission_files/cluster_out/out_recovertest_001_B0_30_S0_3_T490000.equ.o
#$ -q all.q@compute-1-8.local

mpirun -np 1 /home/jh148/lammps-26Jan2014-GPU2/bin/lmp_openmpi -in ./lammps_inputs/equilibration/equilibration.inp -sf gpu -var GPU 1 -var usic recovertest -var trial 001 -var namestring B0_30_S0_3 -var Regime 0 -var ts 1 -var steps_equ 10000 -var run_phase 1 -var divide_equ 1 -var set_CheckPoint 0 -var restartf 10000000 -var Temp 490000 -var read_res /Users/SJH/Dropbox/UA_Research/Codes/cppWork/cppWork/simulations/recover/2015/recovertest/simulations/quench/restart/restart_recovertest_001_B0_30_S0_3_T490000.qch.restart -var write_res /Users/SJH/Dropbox/UA_Research/Codes/cppWork/cppWork/simulations/recover/2015/recovertest/simulations/equilibration/restart/restart_recovertest_001_B0_30_S0_3_T490000.equ.restart -log ./equilibration/log/recovertest_001_B0_30_S0_3_T490000.equ.log > ./equilibration/screen/recovertest_001_B0_30_S0_3_T490000.equ.screen
