#!/bin/bash
#$ -V
#$ -cwd
#$ -j y
#$ -pe orte 1
#$ -p 0
#$ -R y
#$ -hold_jid equ_recovertest_001_B0_30_S0_3_T490000
#$ -N prd_recovertest_001_B0_30_S0_3_T490000
#$ -o ./production/submission_files/cluster_out/out_recovertest_001_B0_30_S0_3_T490000.prd.o
#$ -q all.q@compute-1-8.local

mpirun -np 1 /home/jh148/lammps-26Jan2014-GPU2/bin/lmp_openmpi -in ./lammps_inputs/production/production.inp -sf gpu -var GPU 1 -var usic recovertest -var trial 001 -var namestring B0_30_S0_3 -var Regime 0 -var ts 1 -var exp_base 1.2 -var n_prd_blocks 10 -var blocksize 39 -var divide_prd 1 -var set_CheckPoint 0 -var Temp 490000 -log ./production/log/recovertest_001_B0_30_S0_3_T490000.prd.log > ./production/screen/recovertest_001_B0_30_S0_3_T490000.prd.screen
