#!/bin/bash
#$ -V
#$ -cwd
#$ -j y
#$ -pe orte 1
#$ -p 0
#$ -R y
#$ -N gen_recovertest_002_B0_30_S0_3_T500000
#$ -o ./generation/submission_files/cluster_out/out_recovertest_002_B0_30_S0_3_T500000.gen.o
#$ -q all.q@compute-1-9.local

mpirun -np 1 /home/jh148/lammps-26Jan2014-GPU2/bin/lmp_openmpi -in ./lammps_inputs/generation/generation.inp -sf gpu -var GPU 0 -var usic recovertest -var trial 002 -var namestring B0_30_S0_3 -var vseed 675708 -var ts 1 -var steps_gen 1000000 -var types_all 1 2 3 4 5 6 7 8 9 10 11 12 13 14 -var types_heavy 1 2 3 5 6 7 9 10 11 12 14 -var types_light 4 8 13 -var Temp 500000 -log ./generation/log/recovertest_002_B0_30_S0_3_T500000.gen.log > ./generation/screen/recovertest_002_B0_30_S0_3_T500000.gen.screen
