#!/bin/bash
#$ -V
#$ -cwd
#$ -j y
#$ -pe orte 1
#$ -p 0
#$ -R y
#$ -hold_jid gen_recovertest_000_B0_30_S0_3_T500000
#$ -N qch_recovertest_000_B0_30_S0_3
#$ -o ./quench/submission_files/cluster_out/out_recovertest_000_B0_30_S0_3_Regime0.qch.o
#$ -q all.q@compute-1-8.local

mpirun -np 1 /home/jh148/lammps-26Jan2014-GPU2/bin/lmp_openmpi -in ./lammps_inputs/quench/quench.inp -sf gpu -var GPU 0 -var usic recovertest -var trial 000 -var namestring B0_30_S0_3 -var Regime 0 -var n_intervals 7 -var ts 1 -var steps_qch 70000 -var TempA 500000 490000 480000 470000 460000 450000 440000 -var TempB 490000 480000 470000 460000 450000 440000 430000 -var readRestartPath ./generation/restart/restart_recovertest_000_B0_30_S0_3_T500000.gen.restart -log ./quench/log/recovertest_000_B0_30_S0_3_Regime0.qch.log > ./quench/screen/recovertest_000_B0_30_S0_3_Regime0.qch.screen
